# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
        
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/petclinic:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/petclinic:${{ github.sha }}
    - name: Rolling Update
      uses: JamesIves/fetch-api-data-action@releases/v1
      with:
        ENDPOINT: https://beta.gopaddle.io/gateway/v1/application/appsa9fde7b7cb106c486bcb691ca134e64fd14c
        CONFIGURATION: '{ "method": "PUT", "headers": {"Authorization": "Bearer eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJkZW1vQGdvcGFkZGxlLmlvIiwiZXhwIjoxNjExMTgxNzM0LCJqdGkiOiI1MzMxZTc3MGc0N2U4ZzRiNDlnYjQxMmdkZWNiYmMyOGRmNWUiLCJpYXQiOjE2MTExMzg1MzQsImlzcyI6ImdvcGFkZGxlIn0.EP5cxSf7-teZFx_0woLjtdVwQOxf1iS72-u5UY310HO0J-6R7K_HjkBXF4ORFlAMQmeyoW6VxA4OCF_kQwOQvoszTRGMctpSRUDGLNrMzQ2QSJ6PK7kUOI71Ivfn1U_Mc1FvU0FmjO_1a9mwJWM5YMgaM4acxStQ4Ah-QQN_iVHIjG5f4wvUBfGDEtd1-bP_rLekEYtyk973T0gvXFOnGJ67oEoybpu8KZrOeJtmIVjvoTgt8SIYcqEgepwxLNqJVpKi253LbGwGlL2h5uPjjq0vKsTCwwer-4iBONLjl9B2XdytxxtHUsBPFRDOYBF_xDzubVgCoOdXIcgAXgYu0w"},"body":{"updateType":"buildUpdate","deploymentTemplateVersion":"draft","serviceGroups":[{"name":"spring-petclinic","id":"sg63e2f795sg62e6sg4cd7sgbaefsg4e572ff17787","version":"draft","services":[{"id":"svcea1ce6dcdccaccc4c64cabbec84f5b0f495ee","serviceVersion":"draft","releaseConfig":{"image":"${{ secrets.REGISTRY_LOGIN_SERVER }}/petclinic:${{ github.sha }}"}}],"description":"YXBwIGlubGluZSB1cGRhdGUgc3VwcG9ydCBhZGRlZA=="}]}}'
          
